name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - run: arduino-cli core update-index
      - run: arduino-cli core install esp32:esp32
      - run: arduino-cli lib install "ArduinoJson" "ESPAsyncWebServer" "AsyncTCP"
      - run: arduino-cli compile --fqbn esp32:esp32:esp32 ./Tambay-2.0-Vendo
      - run: |
          pip install esptool
          BOOT=$(find ~/.arduino15 -name bootloader_dio_40m.bin | head -n1)
          PART=$(find ~/.arduino15 -name boot_app0.bin | head -n1)
          BIN=$(find./Tambay-2.0-Vendo/build -name "*.bin" | head -n1)
          esptool.py --chip esp32 merge_bin -o Tambay-2.0-Vendo.ino.merged.bin --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 $BOOT 0x8000 $PART 0xe000 $PART 0x10000 $BIN
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add Tambay-2.0-Vendo.ino.merged.bin
          git commit -m "Update BIN" || true
          git push
