name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-arduino-cli@v1
      - run: arduino-cli core update-index
      - run: arduino-cli core install esp32:esp32
      - run: arduino-cli lib install "ArduinoJson" "ESPAsyncWebServer" "AsyncTCP"
      - run: arduino-cli compile --fqbn esp32:esp32:esp32 --build-path /tmp/build./Tambay-2.0-Vendo
      - run: |
          pip install esptool
          BOOT=$(find /tmp/build -name "*bootloader*.bin" | head -n1)
          PART=$(find /tmp/build -name "*.partitions.bin" | head -n1)
          APP0=$(find /home/runner -name "boot_app0.bin" | head -n1)
          BIN=$(find /tmp/build -name "*.ino.bin" | head -n1)
          esptool --chip esp32 merge-bin -o Tambay-2.0-Vendo.ino.merged.bin --flash-mode dio --flash-freq 40m --flash-size 4MB 0x1000 $BOOT 0x8000 $PART 0xe000 $APP0 0x10000 $BIN
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add Tambay-2.0-Vendo.ino.merged.bin
          git commit -m "Update BIN" || true
          git push
