name: Build BIN
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1
      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32
          arduino-cli lib install "LiquidCrystal I2C"
      - name: Make sketch folder
        run: |
          mkdir -p Tambay-2.0-Vendo
          cp Tambay-2.0-Vendo.ino Tambay-2.0-Vendo/ 2>/dev/null || true
          cp Tambay-2.0-Vendo/ 2>/dev/null || true
      - name: Compile
        run: arduino-cli compile --fqbn esp32:esp32:esp32 Tambay-2.0-Vendo --export-binaries
      - name: Upload BIN
        uses: actions/upload-artifact@v4
        with:
          name: Tambay-2.0-BIN
          path: Tambay-2.0-Vendo/build/**/*.bin
